"""Utility for managing apicov data directory in the project."""

from pathlib import Path
from typing import Self

_GITIGNORE_CONTENT = """\
# Automatically created by apicov
*
"""

_README_CONTENT = """\
# apicov working directory

This directory contains trace files and reports generated by [apicov].

You probably do not want to commit this to version control.

[apicov]: https://github.com/petuzk/apicov
"""

_BOILERPLATE_FILES = {
    ".gitignore": _GITIGNORE_CONTENT,
    "README.md": _README_CONTENT,
}


class ApicovDataDir:
    """Path-like object responsible for managing apicov data directory."""

    DEFAULT_DIRNAME = ".apicov"

    @classmethod
    def at(cls, path: str | Path | None = None) -> Self:
        """Get an ApicovDataDir at the given parent path, or in current working directory."""
        return cls(Path(path or Path.cwd(), cls.DEFAULT_DIRNAME))

    def __init__(self, path: str | Path) -> None:
        self.path = Path(path).absolute()

    def __fspath__(self) -> str:
        return str(self.path)

    def __truediv__(self, other: str | Path) -> Path:
        return self.path / other

    def ensure(self) -> Self:
        """Ensure that the directory exists and is ready for writing into."""
        if not self.path.is_dir():
            self.path.mkdir()

        for filename, content in _BOILERPLATE_FILES.items():
            pth = self.path / filename
            if not pth.exists():
                pth.write_text(content)

        return self
